print(" this is the general knowledge quiz!!!")

question = input(" 1. What is the capital city of France? ")
if question == "paris":
    print(" correct answer !")
else:
    print(" incorrect answer !")        
print(" 2. What is the largest planet in our solar system? ")
question2 = input()
if question2 == "jupiter":
    print(" correct answer !")
else:
    print(" incorrect answer !")       
print(" 3. Who wrote the play 'Romeo and Juliet'? ")
question3 = input()
if question3 == "shakespeare":
    print(" correct answer !")
else:
    print(" incorrect answer !")
print(" 4. What is the chemical symbol for gold? ")
question4 = input()
if question4 == "au":
    print(" correct answer !")
else:
    print(" incorrect answer !")
print(" 5. What is the largest mammal in the world? ")
question5 = input()
if question5 == "blue whale":
    print(" correct answer !")
else:
    print(" incorrect answer !")
print(" 6. Who painted the Mona Lisa? ")
question6 = input()
if question6 == "leonardo da Vinci":
    print(" correct answer !")
else:
    print(" incorrect answer !")    
print(" 7. What is the smallest country in the world? ")
question7 = input()         
if question7 == "vatican city":
    print(" correct answer !")
else:
    print(" incorrect answer !")
print(" 8. Who is the current President of the United States? ") 
question8 = input()
if question8 == "joe biden":    
    print(" correct answer !")
else:
    print(" incorrect answer !")    
print(" 9. What is the largest ocean on Earth? ")
question9 = input()
if question9 == "pacific ocean":
    print(" correct answer !")
else:
    print(" incorrect answer !")
print(" 10. Who is the author of the Harry Potter book series? ")
question10 = input()    
if question10 == "j.k. rowling":
    print(" correct answer !")
else:
    print(" incorrect answer !")
print(" thank you for taking the quiz !")